### ISSUE TITLE
does this work with parsedown packages or is composer required?

### ISSUE THREAD

**Issue by sascha-wi** [kuenzign/WikiMarkdown#12]
See title, I am looking to use markdown on our mediawiki instance. But I don't want to install unnecessary libraries which come with composer. So is it possible to install this extension with the use of php-parsedown package e.g. for debian?

**Comment by kuenzign** [comment]
I've never tried using anything other than composer.  You are welcome to try using alternative methods of installing the dependencies needed for this extension, but I can't guarantee they will work.

**Comment by sascha-wi** [comment]
Hm thats sad to hear, esp. since under requirements on this page its nowhere mentioned that composer is **required**. Also its mentioned that you could install the parsedown "manually" so I assumed that would be possible.

Also the install instructions here https://www.mediawiki.org/wiki/Extension:WikiMarkdown#Configuration are different from whats shown on this github
I am not sure where the discrepancy stems from.

**Comment by kuenzign** [comment]
I'm sure that as long as you have parsedown installed and the extension is able to access it, you will be able to use it, but I've not personally tried that as composer is the preferred method.

**Comment by sascha-wi** [comment]
Still I am not sure the installation instructions on this github are leading anywhere? By following them I would simple install the parsedown package from my repos and add `wfLoadExtension( 'WikiMarkdown' );` to LocalSettings.php
Which probably isn't enough to make this extension work. The previously linked wiki page at least mentions cloning this repo...

**Comment by kuenzign** [comment]
You need to download the files for this repo and put them into a folder in your extensions folder for your server just like any other extension install.  The instructions on the wiki page are just more complete.

**Comment by sascha-wi** [comment]
So for debian there is only one php-parsedown package, I think extended and extra are part of backports, so we will not use them for now. I get this
![2023-05-15_10-50](https://github.com/kuenzign/WikiMarkdown/assets/123939946/01a6db52-e00c-4a9c-b571-f8dc8ee5085e)
![2023-05-15_10-52](https://github.com/kuenzign/WikiMarkdown/assets/123939946/c8fb6e3c-f305-44f1-b817-35babf496b0e)

 content drop down when editing pages but when entering any markdown syntax its not showing up. When using <markdown> tags on the source code it throws this error when trying to save.

**Comment by sascha-wi** [comment]
I assume you are referring to the source editor? That is the one I used in the previous comment, where I received the Internal error.

**Comment by kuenzign** [comment]
Okay, then can you add `$wgShowExceptionDetails = true;` to your LocalSettings.php and see if that provides a better error message to diagnose the issue?

**Comment by sascha-wi** [comment]
`[0cdca3b43efdd41cbe61ea28] /index.php?title=IT:Abteilungsbesprechung_20230427&action=submit Error from line 330 of /var/www/wiki.intern.weizenbaum-institut.de/extensions/WikiMarkdown/includes/WikiMarkdown.php: Class 'Parsedown' not found

Backtrace:

#0 /var/www/wiki.intern.weizenbaum-institut.de/extensions/WikiMarkdown/includes/WikiMarkdown.php(215): WikiMarkdown::getParsedown()
#1 /var/www/wiki.intern.weizenbaum-institut.de/extensions/WikiMarkdown/includes/WikiMarkdown.php(46): WikiMarkdown::parseMarkdown()
#2 /var/www/wiki.intern.weizenbaum-institut.de/includes/parser/Parser.php(3922): WikiMarkdown::parserHook()
#3 /var/www/wiki.intern.weizenbaum-institut.de/includes/parser/PPFrame_Hash.php(330): Parser->extensionSubstitution()
#4 /var/www/wiki.intern.weizenbaum-institut.de/includes/parser/Parser.php(2887): PPFrame_Hash->expand()
#5 /var/www/wiki.intern.weizenbaum-institut.de/includes/parser/Parser.php(1556): Parser->replaceVariables()
#6 /var/www/wiki.intern.weizenbaum-institut.de/includes/parser/Parser.php(651): Parser->internalParse()
#7 /var/www/wiki.intern.weizenbaum-institut.de/includes/content/WikitextContent.php(374): Parser->parse()
#8 /var/www/wiki.intern.weizenbaum-institut.de/includes/content/AbstractContent.php(590): WikitextContent->fillParserOutput()
#9 /var/www/wiki.intern.weizenbaum-institut.de/includes/EditPage.php(4282): AbstractContent->getParserOutput()
#10 /var/www/wiki.intern.weizenbaum-institut.de/includes/EditPage.php(4187): EditPage->doPreviewParse()
#11 /var/www/wiki.intern.weizenbaum-institut.de/includes/EditPage.php(2965): EditPage->getPreviewText()
#12 /var/www/wiki.intern.weizenbaum-institut.de/includes/EditPage.php(701): EditPage->showEditForm()
#13 /var/www/wiki.intern.weizenbaum-institut.de/includes/actions/EditAction.php(71): EditPage->edit()
#14 /var/www/wiki.intern.weizenbaum-institut.de/includes/actions/SubmitAction.php(38): EditAction->show()
#15 /var/www/wiki.intern.weizenbaum-institut.de/includes/MediaWiki.php(527): SubmitAction->show()
#16 /var/www/wiki.intern.weizenbaum-institut.de/includes/MediaWiki.php(313): MediaWiki->performAction()
#17 /var/www/wiki.intern.weizenbaum-institut.de/includes/MediaWiki.php(940): MediaWiki->performRequest()
#18 /var/www/wiki.intern.weizenbaum-institut.de/includes/MediaWiki.php(543): MediaWiki->main()
#19 /var/www/wiki.intern.weizenbaum-institut.de/index.php(53): MediaWiki->run()
#20 /var/www/wiki.intern.weizenbaum-institut.de/index.php(46): wfIndexMain()
#21 {main}
`
I guess the php-parsedown package is not working?

**Comment by kuenzign** [comment]
Yes that is indeed the case.  I'm not certain what it would take to get MediaWiki to be able to access Parsedown via php-parsedown.   Composer works well, but if you don't want to use that then I'm not certain what you need to do.

**Comment by mjsir911** [comment]
btw, this is kind of a kludge but does work for me to get things running without composer:

in localsettings.php
```php
require_once("<parsedown path>/Parsedown.php");
```

**Comment by sascha-wi** [comment]
> kludge

Can you elaborate why you describe this solution as a such? I haven't tried it yet, but really would like to get markdown running for our mediawiki without composer.
